name: Deploy Spring Boot to Docker Hub

on:
  push:
    branches: [ "main" ] # Kích hoạt tự động khi Push code lên nhánh main

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Mượn máy ảo Ubuntu của GitHub để chạy

    steps:
      - name: Bước 1 - Tải mã nguồn (Checkout code)
        uses: actions/checkout@v4

      - name: Bước 2 - Đăng nhập vào Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bước 3 - Build và Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Chỉ định thư mục gốc chứa Dockerfile
          push: true # Cho phép đẩy thẳng lên Docker Hub sau khi Build xong
          
          # Cấu hình đánh Tags cho Image
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:latest